// <auto-generated />
namespace HostelApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_columns_LivingROOM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_columns_LivingROOM));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191922453_Create_columns_LivingROOM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
